CFLAGS=-Wall -g
LOADLIBES=-lpthread

all: cpu mem threads-race threads-sync threads-atomic write read

.PHONY: clean

clean:
	rm -f cpu mem threads-race threads-sync threads-atomic write read
	rm -f cpu.exe mem.exe threads-race.exe threads-sync.exe threads-atomic.exe write.exe read.exe
